### ISSUE TITLE
Can't install with Python 3.5?

### ISSUE THREAD

**Issue by stain** [edeposit/isbn_validator#1]
```
(venv3) stain@biggie:~/src/cwltool$ pip install isbn_validator
Collecting isbn_validator
  Downloading https://files.pythonhosted.org/packages/05/d2/220b6d5d93879b17725a82a7d82c1b87ff9874b62f0e55bd53db6c4a7cdc/isbn_validator-1.0.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-jmvfe85t/isbn-validator/setup.py", line 5, in <module>
        from docs import getVersion
      File "/tmp/pip-build-jmvfe85t/isbn-validator/docs/__init__.py", line 15
        lambda (x, y):
               ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-jmvfe85t/isbn-validator/

(venv3) stain@biggie:~/src/cwltool$ pip --version
pip 9.0.3 from /home/stain/src/cwltool/venv3/lib/python3.5/site-packages (python 3.5)

```

**Comment by GLMeece** [comment]
FWIW, I've made [a fork that works/installs under Python 3.7](https://github.com/GLMeece/isbn_validator/tree/python_3_7).

I've also created [a Pull Request](https://github.com/edeposit/isbn_validator/pull/2). We'll see how it goes!

**Comment by milossramek** [comment]
The same with Python 3.9 :(
